-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Veterinario (
CRMU VARCHAR(10) PRIMARY KEY,
nome VARCHAR(10)
)

CREATE TABLE cor (
cor_PK INTEGER,
cor VARCHAR(10),
Cod_FK VARCHAR(),
PRIMARY KEY(cor_PK,Cod_FK)
)

CREATE TABLE Consulta_REALIZA (
dt VARCHAR(10),
Hr VARCHAR(10),
Cod VARCHAR(10),
CRMU VARCHAR(10),
PRIMARY KEY(dt,Cod,CRMU),
FOREIGN KEY(CRMU) REFERENCES Veterinario (CRMU)
)

CREATE TABLE fone (
fone_PK INTEGER,
fone VARCHAR(10),
CRMU_FK VARCHAR(),
PRIMARY KEY(fone_PK,CRMU_FK),
FOREIGN KEY(CRMU_FK) REFERENCES Veterinario (CRMU)
)

CREATE TABLE Pet (
Cod VARCHAR(10) PRIMARY KEY,
raca VARCHAR(10),
nome VARCHAR(10)
)

CREATE TABLE Receita (
NrComtrole VARCHAR(10) PRIMARY KEY,
prescricao VARCHAR(10),
medicacao VARCHAR(10)
)

CREATE TABLE tem (
NrComtrole VARCHAR(10),
CRMU VARCHAR(),
cor_PK VARCHAR(),
PRIMARY KEY(NrComtrole,CRMU,cor_PK),
FOREIGN KEY(NrComtrole) REFERENCES Receita (NrComtrole),
FOREIGN KEY(/*erro: ??*/) REFERENCES Consulta_REALIZA (dt,Cod,CRMU)
)

ALTER TABLE cor ADD FOREIGN KEY(Cod_FK) REFERENCES Pet (Cod)
ALTER TABLE Consulta_REALIZA ADD FOREIGN KEY(Cod) REFERENCES Pet (Cod)
