//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class jogos
    {
        public int C_ID { get; set; }
        public string Nome { get; set; }
        public string Plataforms { get; set; }
        public string ClassificacaoIndicativa { get; set; }
        public string Modes { get; set; }
        public string Generos { get; set; }
    }
}
